// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCity.Infrastructure.Data;

#nullable disable

namespace SmartCity.Infrastructure.Migrations
{
    [DbContext(typeof(SmartCityDbContext))]
    [Migration("20251228172800_SeedCityMetrics")]
    partial class SeedCityMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartCity.Domain.Entities.CityMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CityMetrics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0be4b48b-b3bc-4fa8-8799-6dcb935990e5"),
                            Location = "Jyväskylä Center",
                            Timestamp = new DateTime(2025, 12, 28, 17, 27, 59, 683, DateTimeKind.Utc).AddTicks(3731),
                            Type = 1,
                            Value = 72.0
                        },
                        new
                        {
                            Id = new Guid("9646e955-d25b-4684-bff1-e029e179e03a"),
                            Location = "Lutakko",
                            Timestamp = new DateTime(2025, 12, 28, 17, 27, 59, 683, DateTimeKind.Utc).AddTicks(3734),
                            Type = 2,
                            Value = 41.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
